common-queue/src/main/java/org/duracloud/common/queue/aws/SQSTaskQueue.java
common-sns/src/main/java/org/duracloud/common/sns/SnsSubscriptionManager.java
common-sns/src/main/java/org/duracloud/common/sns/config/SnsSubscriptionManagerConfig.java
common-sns/src/main/java/org/duracloud/common/sns/impl/AccountChangeNotifierImpl.java

The SNS and SQS client were created using the deprecated Client constructor. This mean that only credentials can be picked up with the delegation AWS SDK process (JVM variables, env var, EC2 IAM Role).
The proposed changes allow to force the use of a region specifying an ENV var AWS_REGION or a aws.region JVM variable
This is a replacement of the #23 
- I have applied the requested changes
- it is against the develop branch instead then the master

DURACLOUD-1141 Allow to use SNS and SQS services in region different than us-east-1

---

durastore/src/main/java/org/duracloud/durastore/util/TaskProviderFactoryImpl.java
s3storageprovider/src/main/java/org/duracloud/s3storage/S3ProviderUtil.java
s3storageprovider/src/main/java/org/duracloud/s3storage/S3StorageProvider.java
storageprovider/src/main/java/org/duracloud/storage/domain/StorageAccount.java

The S3StorageProvider now can specify as option the region to use. It is backward compatible, empty option are treat as before (default to us-east-1).
See also duracloud/management-console#7 for the changes required to the mgm console
This PR replaces #22 as it is against the develop branch instead than the master

DURACLOUD-1142 Allow to configure the region for the S3 Storage provider

---

chunk/src/main/java/org/duracloud/chunk/stream/KnownLengthInputStream.java
chunk/src/test/java/org/duracloud/chunk/stream/KnownLengthInputStreamTest.java

Resovles:  https://jira.duraspace.org/browse/DURACLOUD-1147

Chunk manifests no longer fail when content id contains UTF-8 chars.

---

chunk/src/main/java/org/duracloud/chunk/writer/DuracloudContentWriter.java
chunk/src/test/java/org/duracloud/chunk/writer/DuracloudContentWriterTest.java
synctool/src/test/java/org/duracloud/sync/endpoint/DuraStoreChunkSyncEndpointTest.java

Ensure that previously unchunked file is removed when overwritten by a chunked version of the identically named but differently checksummed file.
This fix can be tested using the following steps:
1. create a 2 MB file (fileA).
2. use the synctool.jar  to upload the file.
3. change the file by appending some text to it, e.g. echo "test" >> file
4. use the synctool again, but this time specify 1 MB chunks with the "-m 1m" parameters.
5. verify that there are three chunks (fileA.dura-chunk-0000-0002), and a fileA.dura-manifest 
6. verify that fileA has been deleted.

Duracloud 840

---

notification-amazon/src/main/java/org/duracloud/notification/AmazonNotificationFactory.java
pom.xml

The SES Email Service is created using the deprecated constructor that doesn't follow the region preference expressed on variable environment, etc. 
An additional issue is related to the forced use of explicit username/password without the possibility to rely on IAM roles
To be backward compatible I check if the credentials are provided in the configuration file and if so, they will be used. Otherwise, the default AWS Credentials chain is used that in turn mean the ability to use IAM role

DURACLOUD-1146 Allow to use SES service in any region with IAM role

---

s3storageprovider/src/main/java/org/duracloud/s3storage/S3StorageProvider.java

when retrying after possible S3StorageProvider.addContent() failure.

Correctly reports total number of seconds waited in the log

---

chunk/src/main/java/org/duracloud/chunk/manifest/ChunksManifest.java
chunk/src/main/java/org/duracloud/chunk/stream/KnownLengthInputStream.java
chunk/src/test/java/org/duracloud/chunk/stream/KnownLengthInputStreamTest.java

Resolves test failure on Windows due to default encoding

Ensures KnownLengthInputStream uses UTF-8 encoding for length calculation

---

common/src/test/java/org/duracloud/common/util/ChecksumUtilTest.java
duradmin/src/main/java/org/duracloud/duradmin/util/SpaceUtil.java
durastore/src/main/java/org/duracloud/durastore/rest/ContentRest.java
durastore/src/main/java/org/duracloud/durastore/rest/ManifestRest.java
durastore/src/test/java/org/duracloud/durastore/rest/ManifestRestTest.java
s3storageprovider/src/main/java/org/duracloud/s3storage/S3StorageProvider.java
storageprovider/src/main/java/org/duracloud/storage/provider/StorageProviderBase.java
storeclient/src/main/java/org/duracloud/client/ContentStoreImpl.java
storeclient/src/main/java/org/duracloud/client/HttpHeaders.java
storeclient/src/test/java/org/duracloud/client/ContentStoreImplTest.java

Under the hood this commit is actually doing a bit more than simply adding Content-Encoding header to the generated manifest properties.
Content-Encoding support has been added to the StorageProvider, DuraStore, storeclient, and DurAdmin.  The ContentEncoding value is stored natively with the S3 api using the ObjectMetadata.contentEncoding property (rather than using generic object properties). When using the REST interface passing the Content-Encoding header on a POST will cause that header and value to appear on a subsequent GET.    Finally DuraAdmin allows users to add and remove the Content-Encoding property via the property editor.
Test: 
1.  Generate a manifest for an existing space and verify that the URI identified by the returned Location header contains the "Content-Encoding: …

Adds the "Content-Encoding: gzip" to the generated manifest properties.

---

duradmin/src/main/webapp/jquery/dc/widget/ui.propertiesviewer.js
duradmin/src/main/webapp/jquery/dc/widget/ui.tagsviewer.js
duradmin/src/main/webapp/js/spaces-manager.js
duradmin/src/main/webapp/style/base.css
durastore/src/main/java/org/duracloud/durastore/error/ResourcePropertiesInvalidException.java
durastore/src/main/java/org/duracloud/durastore/rest/ContentResourceImpl.java
durastore/src/main/java/org/duracloud/durastore/rest/ContentRest.java
durastore/src/test/java/org/duracloud/durastore/rest/ContentResourceImplTest.java
synctool/src/main/java/org/duracloud/sync/endpoint/DuraStoreSyncEndpoint.java

This PR addresses https://jira.duraspace.org/browse/DURACLOUD-752. 
There are changes to three areas: 
1. Duradmin
2. DuraStore
3. Synctool
Duradmin Test:
1. Create a content item.
2. Attempt to update  the properties or tags with non-us ascii characters.
3. Verify that there is an appropriate validation message and you are unable to submit the form.
DuraStore test
1. curl -v -X POST -H "x-dura-meta-test-1234: 无常" http://host:8080/durastore/yourspace/item.jpg?storeID=52 --data-binary "@item.jpg"
2. Verify that  a 400 BAD Request with description message is returned.
3. curl -v -X POST -H "x-dura-meta-test-1234: test" http://host:8080/durastore/yourspace/item.jpg?storeID=52 --data-binary "@item.jpg"
4. Verify that  a  201 is returned. 
5. curl -v -X POST -H "x-dura-meta-test-1234: 无常" …

Properly handle UTF-8 characters in content properties

---

retrievaltool/src/main/java/org/duracloud/retrieval/RetrievalTool.java
retrievaltool/src/main/java/org/duracloud/retrieval/util/StoreClientUtil.java
storeclient/src/main/java/org/duracloud/client/ContentStoreManagerImpl.java

1. username/password is invalid
2. host is invalid
3. storeId is invalid
4. other runtime exceptions occur
Resolves: https://jira.duraspace.org/browse/DURACLOUD-1143
To test: 
1.  build the source.
2. test bad username password:
` java -jar target/retrievaltool-4.5.0-SNAPSHOT-driver.jar -u <username>  -p <bad password>  -h <host> -s <spaceId>  -c <content dir>`
3. verify response is accurate and legible.
4.  test bad host: 
` java -jar target/retrievaltool-4.5.0-SNAPSHOT-driver.jar -u <username>  -p <password>  -h <bad host> -s <spaceId>  -c <content dir>`
5. verify response is accurate and legible.
6.  test bad storeId: 
` java -jar target/retrievaltool-4.5.0-SNAPSHOT-driver.jar -u <username>  -p <password>  -h <host> -s <spaceId>  -i <bad storeId> -c <content dir>`
8. verify response is …

Ensures that a legible error message is produced by retrieval tool when:

---

common/src/main/java/org/duracloud/common/web/RestHttpHelper.java
integration/src/test/java/org/duracloud/integration/client/TestContentStore.java
retrievaltool/src/main/java/org/duracloud/retrieval/mgmt/RetrievalManager.java
retrievaltool/src/main/java/org/duracloud/retrieval/mgmt/RetrievalWorker.java
retrievaltool/src/main/java/org/duracloud/retrieval/util/StoreClientUtil.java
storeclient/src/main/java/org/duracloud/client/ContentIterator.java
storeclient/src/main/java/org/duracloud/client/ContentStore.java
storeclient/src/main/java/org/duracloud/client/ContentStoreImpl.java
storeclient/src/main/java/org/duracloud/client/ContentStoreManagerImpl.java
storeclient/src/main/java/org/duracloud/client/PartialContentRetryInputStream.java
storeclient/src/test/java/org/duracloud/client/ContentStoreImplTest.java

**Adds support for range requests and automatic retrying of midstream failures from point of failure.**
* * *
**JIRA Ticket**:https://jira.duraspace.org/browse/DURACLOUD-1191
https://jira.duraspace.org/browse/DURACLOUD-1208
Adds support in the storeclient for performing range requests on content streams.
Additionally now streams are automatically resumed from a point of failure in the case of
an IOException encountered in midstream.
All users of the storeclient (including the retrievaltool) will automatically benefit from
this improvement as momentarily network failures will not trigger redownloading of an entire
file (be it a chunk or otherwise).
There are unit and integration tests covering the functionality. …

Duracloud 1191: Adds support for range requests and automatic retrying of midstream failures from point of failure.

---

s3storageprovider/src/main/java/org/duracloud/s3storage/S3ProviderUtil.java

**JIRA Ticket**:
Follow on to https://jira.duraspace.org/browse/DURACLOUD-1219. The updated client requires a default region setting.
Checks for a Java system property named AWS_REGION for the default region value. If there is no property with that key set, the region is set to null, which allows for the client to pick up the region from the environment (as an environment variable or from an aws config file).
Deploy the web applications without setting AWS_REGION, verify that there are region errors. Add the AWS_REGION system property, verify that DurAdmin loads correctly.
@dbernstein

Sets the region in the S3Client based on AWS_REGION system property

---

s3storageprovider/src/main/java/org/duracloud/s3storage/S3ProviderUtil.java
s3storageprovider/src/test/java/org/duracloud/s3storage/S3ProviderUtilTest.java

**JIRA Ticket**:
https://jira.duraspace.org/browse/DURACLOUD-1222
Ensures that S3 clients that are created with different optional parameters (primarily region) result in distinct entries in the cache.
Create a storage provider with a region setting. Verify that buckets created for that provider are in the expected region. Change the region setting. Verify that buckets created for the provider are in the new region.
Example:
* Does this change require documentation to be updated?  No
@dbernstein

DURACLOUD-1222: Ensures that S3 client cache differentiates between clients with different options (primarily region)

---

durastore/src/main/java/org/duracloud/durastore/util/ACLStorageProvider.java

**JIRA Ticket**: https://jira.duraspace.org/browse/DURACLOUD-1225
Removes the call in ACLStorageProvider.setContentProperties() that sends a notification to DuraStore/DurAdmin to reset the account cache.
Once deployed, verify that when making a call to set content properties an SQS message does not get sent with type STORAGE_PROVIDER_CACHE_ON_NODE_CHANGED
Example:
* Does this change require documentation to be updated?  No
* Does this change add any new dependencies?  No
Tag (@ mention) interested parties or, if unsure, …

Removes call to send notification to clear account cache when content properties are updated

---

storeclient/src/main/java/org/duracloud/client/ContentStoreImpl.java

The specific error message called out in the ticket (https://jira.duraspace.org/browse/DURACLOUD-1065) was addressed in another commit (683e561d35eafdde5c3decabf1c4f80f591a3fe1 - c.f. https://jira.duraspace.org/browse/DURACLOUD-1094). In the same spirit this commit changes a WARN to DEBUG in order to reduce noise in the log output.
Resolves:  https://jira.duraspace.org/browse/DURACLOUD-1065
1.  Run the synctool against an empty space. 
2. Verify the noisy WARN messages do not appear in the work/logs/complete.log file.
@bbranan

Reduce noise in logs

---

.travis.yml

**JIRA Ticket**: https://jira.duraspace.org/browse/DURACLOUD-1243
Specifies Ubuntu 14.04 Trusty as the required Travis build environment. The Trusty environment is required because it supports Oracle Java 8 whereas Ubuntu 16.04 Xenial does not.
If the CI build passes we should be good to go.

DURACLOUD-1243: Specifies Ubuntu 14.04 Trusty as Travis build environment

---

duradmin/src/main/webapp/js/spaces-manager.js

**JIRA Ticket**: https://jira.duraspace.org/browse/DURACLOUD-1237
Moves the streaming panel to the bottom of panels and restricts its display to the S3 storage provider.
Deploy Duracloud and observe that the streaming panel only appears for S3 storage providers and has moved to the bottom of the display.
Example:
Tag (@ mention) interested parties or, …

Duracloud 1237: moves streaming panel to the bottom of panels and restricts display to the S3 storage provider

---

.travis.yml
duradmin/src/main/webapp/WEB-INF/jsp/spaces/spaces-manager.jsp
duradmin/src/main/webapp/js/spaces-manager.js

**Adds limits to space deletion process so that only root users can select multiple spaces, and all users must type in the name of the space to delete it.**
* * *
**JIRA Ticket**: https://jira.duraspace.org/browse/DURACLOUD-1192
This PR makes the following changes: 1) limits selecting multiple spaces simultaneously for deletion to root users and 2) adds a dialog window to the deletion process that warns users of the severity of their actions and requires them to type in the name of the space they want to delete before deleting it.
- Deploy Duracloud and log in as a root user and then as a non-root users. Verify that multiple spaces can only be selected in the case of the former. Then select a space and click the …

Duracloud 1192: changes to space deletion process

---

duradmin/src/main/webapp/WEB-INF/jsp/layout/v2/base.jsp
duradmin/src/main/webapp/js/spaces-manager.js

**JIRA Ticket**: https://jira.duraspace.org/browse/DURACLOUD-398
Disables cursor hot keys in jQuery UI Layout panes, so that Shift + [arrow keys] doesn't do anything.
Deploy Duracloud and try Shift + [arrow keys]. The UI should not change in random ways.
Example:

Duracloud-398: Disable cursor hot keys across all panes

---

synctool/content/my-file.txt
synctool/src/main/java/org/duracloud/sync/endpoint/DuraStoreChunkSyncEndpoint.java
synctool/src/test/java/org/duracloud/sync/endpoint/DuraStoreChunkSyncEndpointTest.java

**Post update chunk clean up**
* * *
**JIRA Ticket**: https://jira.duraspace.org/browse/DURACLOUD-1154 and https://jira.duraspace.org/browse/DURACLOUD-1155
This commit ensures that chunked and unchunked content is clean up after an update in the following cases:
1) When replacing a chunked file with another chunked file with fewer chunks, the orphaned chunks are now removed.
2) Whn replacing a chunked file with an unchunked file,  the chunked file is removed.
3) When replacing an unchunked file with an chunked file, the unchunked file is removed.
1. upload a 1K unchunked file (fileA) to space (spaceA)
2. create a 1025 MB file named fileA and sync to duracloud using the sync tool.
3. verify that the unchunked …

duracloud-1155 and duracloud-1154: Post update chunk clean up

---

duradmin/src/main/webapp/js/spaces-manager.js
resources/beanstalk/.ebextensions/elasticbeanstalk.conf

**Fixes 404 error when content ID contains forward slashes in two ways.**
* * *
**JIRA Ticket**: https://jira.duraspace.org/browse/DURACLOUD-1203
- Apache 2.4 config: http://httpd.apache.org/docs/2.4/mod/core.html#allowencodedslashes
There are two strategies included in this PR, and either of them fixes the problem by itself. I've included both to provide options and get the discussion started. The error is coming from Apache, and there is a configuration setting that allows for the %2F encoding. If there are security issues with that then the slashes can be decoded separate from the other special characters. 
Deploy Duracloud, select a content item with a forward slash in the ID. Hit the refresh button in the …

Duracloud 1203: Fixes 404 error when content ID contains forward slashes

---

durastore/src/main/java/org/duracloud/durastore/rest/SpaceResource.java
durastore/src/main/java/org/duracloud/durastore/rest/SpaceRest.java
s3storageprovider/src/main/java/org/duracloud/s3storage/S3StorageProvider.java
storageprovider/src/main/java/org/duracloud/storage/error/SpaceAlreadyExistsException.java
storageprovider/src/main/java/org/duracloud/storage/provider/StorageProviderBase.java

**JIRA Ticket**: https://jira.duraspace.org/browse/DURACLOUD-1245
Calls to the Create Space endpoint that specified the name of an existing space used to generate 500 errors. This allows those same calls to get the same 201 response that the original call received but without making any changes to storage. This allows retries of space creation calls to complete successfully.
Retry logic is also added to a few S3 calls to reduce the potential for failure when performing those calls.
* Perform multiple create space calls with the same parameters. The response should be the same each time. (201 with a Location header)
@dbernstein @nwoodward

DURACLOUD-1245 - Allows retry calls to create space to respond with a 201

---

durastore/src/main/java/org/duracloud/durastore/rest/StorageStatsResource.java
durastore/src/test/java/org/duracloud/durastore/rest/StorageStatsResourceTest.java

are being calculated properly.
Resolves: https://jira.lyrasis.org/browse/DURACLOUD-1248
The previous date calculation logic was not producing the expected results (for reasons that I still don't understand).   
It is covered by a new unit test.
@bbranan

Ensures that start and end times for daily storage stat reports

---

storeclient/src/main/java/org/duracloud/client/ContentStoreImpl.java
storeclient/src/test/java/org/duracloud/client/ContentStoreImplTest.java

**JIRA Ticket**: https://jira.lyrasis.org/projects/DURACLOUD/issues/DURACLOUD-1252
In order to comply with HTTP standard RFC7230 we should handle all HTTP
headers in a case-insensitive manner.
This commit changes all instances where we are comparing headers to `equalsIgnoreCase()` instead of `equals()`.
I changed one of the unit tests to use a lower case header, tests still pass.
We were having issues with missing elements in the UI when load balancing with HAProxy (HAProxy makes all headers lower case). This change has fixed all those issues.
@bbranan

Handle headers case-insensitive

---

resources/travis/before-install.sh
resources/travis/mvndeploy-settings.xml
synctoolui/pom.xml
synctoolui/src/main/install/installbuilder.xml

**Enables 64 bit builds of the macos installer **
* * *
**JIRA Ticket**: https://jira.lyrasis.org/browse/DURACLOUD-1247
You'll need to install the latest install builder  (19.12.0) and update your  installbuilder.executable.path parameter (-D installbuilder.executable.path=...) when building the synctool.
`mvn clean install -Pinstallers  -D installbuilder.executable.path=...` 
Execute the installer on OSX 10.15 or greater
`open synctoolui/target/duracloudsync-6.2.0-SNAPSHOT-osx-installer.app`

Duracloud 1247

---

common-json/pom.xml
common-json/src/main/java/org/duracloud/common/json/JaxbJsonSerializer.java
duradmin/src/main/java/org/duracloud/duradmin/spaces/controller/SnapshotController.java
duradmin/src/test/java/org/duracloud/duradmin/spaces/controller/SnapshotControllerTest.java
durastore/src/main/java/org/duracloud/durastore/aop/SnapshotAccessAdvice.java
pom.xml

This removes the older jackson dependencies which provided xml serialization/mapping utilities and pulls in the equivalent fasterxml dependency which uses the defined jackson version.
@bbranan

Update jackson 1.9 dependencies to defined jackson version

---

resources/travis/before-install.sh

In the 6.2.0 release, these variables were not read properly, causing the installers not to be created as part of the tag build in Travis CI.

Backs out use of variables in Travis InstallBuilder installation script

---

pom.xml

**Update Jetty to latest minor release of version 9.4**
* * *
**JIRA Ticket**: https://jira.lyrasis.org/browse/DURACLOUD-1270
Updates the Jetty Server to the latest minor version to improve performance and compatibility with newer versions of Java.
Build the SyncTool and test syncing directories and files with a space in DuraCloud.
Example: …

DURACLOUD-1270: Update Jetty version 9.4.14 -> 9.4.31

---

retrievaltool/src/main/java/org/duracloud/retrieval/mgmt/CSVFileOutputWriter.java
retrievaltool/src/main/java/org/duracloud/retrieval/mgmt/LoggingOutputWriter.java
retrievaltool/src/main/java/org/duracloud/retrieval/mgmt/OutputWriter.java
retrievaltool/src/main/java/org/duracloud/retrieval/mgmt/RetrievalWorker.java
retrievaltool/src/main/java/org/duracloud/retrieval/mgmt/StatusManager.java
retrievaltool/src/main/java/org/duracloud/retrieval/source/DuraStoreRetrievalSource.java
retrievaltool/src/main/java/org/duracloud/retrieval/source/DuraStoreSpecifiedRetrievalSource.java
retrievaltool/src/main/java/org/duracloud/retrieval/source/DuraStoreStitchingRetrievalSource.java
stitch/src/main/java/org/duracloud/stitch/error/MissingContentException.java
stitch/src/main/java/org/duracloud/stitch/impl/FileStitcherImpl.java

**During the retrieval process, check for missing content and provide the user with an error message and a count of missing files at the end.**
* * *
**JIRA Ticket**: https://jira.lyrasis.org/browse/DURACLOUD-1267
Adds a check that the content IDs in a list-file actually exist in the space.
1. Create a new space and upload a few files to it
2. Create a local text file with a list of the filenames
3. Add an additional filename that doesn't exist in the space to the list, e.g. foo.txt
4. Run a retrieval job on the command line with the local text file specified (-f)
5. Observe the retrieval logs for expected exception messages and note that the final output includes a missing files count

Duracloud 1267: Provide feedback when content ID in a list file does not exist in the space

---

durastore/src/main/java/org/duracloud/durastore/rest/AuxRest.java

**Adds SameSite attribute to CloudFront cookies**
* * *
**JIRA Ticket**: https://jira.lyrasis.org/browse/DURACLOUD-1280
This PR adds the "SameSite=None" setting to the 3 CloudFront cookies set as part of the flow for supporting secure HLS streaming. This setting is needed to allow pages with video players to make use of the cookies.
* Build and deploy DuraStore with this change in place
* Turn on Secure HLS streaming for a space: https://wiki.lyrasis.org/display/DURACLOUDDOC/DuraCloud+REST+API#DuraCloudRESTAPI-HTTPLiveStreamingsupport
* Make a call to get the signed cookies url
```
POST http://localhost:8080/durastore/task/get-signed-cookies-url
{
"spaceId" : "<space-with-secure-hls-streaming-enabled>",
"redirectUrl" : "https://developer-tools.jwplayer.com/stream-tester"
}
```
* In the …

DURACLOUD-1280: Add the SameSite attribute to CloudFront cookies

---

common-rest/src/main/java/org/duracloud/common/rest/HttpHeaders.java
durastore/src/main/java/org/duracloud/durastore/rest/AuxRest.java
durastore/src/main/java/org/duracloud/durastore/rest/TaskRest.java
durastore/src/test/java/org/duracloud/durastore/rest/AuxRestTest.java

**JIRA Ticket**: https://jira.lyrasis.org/browse/DURACLOUD-1293
On requests to the /aux/cookies REST endpoint (which are generally made through CloudFront), the new code looks for the Origin header and uses this to fill and return the Access-Control-Allow-Origin header in the response. This will allow XmlHttpRequest (AJAX) calls to interact with the Aux REST endpoint through Cloudfront as part of the secure HLS workflow.
The Access-Control-Allow-Credentials is also returned with value "true". As noted here: https://developer.mozilla.org/en-US/docs/Web/HTTP/CORS#requests_with_credentials, the Access-Control-Allow-Credentials header is required (in combination with Access-Control-Allow-Origin) to allow XmlHttpRequest to work properly with "credentials" turned on, which is necessary if …

DURACLOUD-1293: Updates /aux/cookies REST call to provide Access-Control-Allow-Origin header

---

synctoolui/src/main/install/README
synctoolui/src/main/install/installbuilder.xml

**JIRA Ticket**: https://jira.lyrasis.org/browse/DURACLOUD-1295
Requires Java 11 as part of the SyncTool installer. Also updates links in the SyncTool installer README
* Attempt to install the SyncTool on a machine with either (1) no Java installed or (2) Java 8 installed
* Verify that the installer indicates that Java 11 is required and opens a download link
* Install Java (either 11 or 15) and retry the installer. This time it should continue with the installation.

DURACLOUD-1295: Updates the SyncTool installer to require Java 11

---

synctoolui/src/main/install/installbuilder.xml

Changes the link set in DURACLOUD-1295 from oracle.com to adoptopenjdk.net
**JIRA Ticket**: An update to https://jira.lyrasis.org/browse/DURACLOUD-1295
Replaces the Java download link presented to users when the SyncTool installer finds that Java 11 is not available on the local system.
Build the SyncTool installer
Remove Java from your path
Run the SyncTool installer, verify that it provides the adoptopenjdk.net download link.

Updates SyncTool installer Java download link

---

swiftstorageprovider/src/main/java/org/duracloud/swiftstorage/SwiftStorageProvider.java

**JIRA Ticket**: [DURACLOUD-1309](https://duracloud.atlassian.net/browse/DURACLOUD-1309)
Filter Content-Type, Content-Length, Last-Modified, and Date metadata out of the Properties section in the web UI.
Swift's letter case of metadata tags does not match what DuraCloud expects and thus it shows up as user defined content properties.
Example in Response Headers:
[x-dura-meta-date|Mon, 07 Jun 2021 17:49:40 GMT]
[x-dura-meta-content-length|11666002]
[x-dura-meta-last-modified|Wed May 12 15:33:47 EDT 2021]
[x-dura-meta-content-type|application/pdf; charset=UTF-8]
To test, these extra metadata should not show up in the Properties section when accessing content stored in Swift storage provider.

Filter out extra Swift metadata

---

chunk/src/main/java/org/duracloud/chunk/manifest/ChunksManifest.java
stitch/src/main/java/org/duracloud/stitch/impl/FileStitcherImpl.java

**This PR changes the file stitching process to handle cases where the index number is missing from entries in a chunk manifest.**
* * *
**JIRA Ticket**: https://duracloud.atlassian.net/browse/DURACLOUD-1310
Adds a comparison between the index number and the number at the end of each chunkId.
1. Use the SyncTool to upload a large file that gets chunked to a DuraCloud space.
2. Modify only the dura-manifest file in the space by removing the `index=X` tag from each <chunk> tag.
3. Use the production version of the RetrievalTool to retrieve the file. It will fail with a checksum mismatch error.
4. Use this snapshot version of the RetrievalTool to retrieve the file.
Tag @duracloud/committers

DURACLOUD-1310: use number in chunkId when index number is possibly missing in a chunk manifest

---

durastore/src/main/java/org/duracloud/durastore/util/AuditConfigBuilder.java

**JIRA Ticket**: https://duracloud.atlassian.net/browse/DURACLOUD-1257
Allows DuraCloud to complete initialization when the audit queue is using SQS rather than RabbitMQ
Use the Management Console to configure the use of SQS for the audit queue. Launch DuraCloud and ensure it comes up properly.
@fozboz

DURACLOUD-1257: Allows audit config to complete init if RabbitMQ is not being used

---

common/src/main/java/org/duracloud/common/constant/Constants.java

This value is repeated in mill. Adding here so it's in a single, central
location.
Related to [DURACLOUD-1304](https://duracloud.atlassian.net/browse/DURACLOUD-1304)

Add default domain constant

---

chunk/src/main/java/org/duracloud/chunk/ChunkableContent.java
chunk/src/main/java/org/duracloud/chunk/writer/FilesystemContentWriter.java
chunk/src/test/java/org/duracloud/chunk/ChunkableContentTest.java
common/src/main/java/org/duracloud/common/util/IOUtil.java
duradmin/src/main/java/org/duracloud/duradmin/spaces/controller/AuditLogController.java
duradmin/src/main/java/org/duracloud/duradmin/spaces/controller/ManifestController.java
durastore/src/test/java/org/duracloud/durastore/util/ACLStorageProviderTest.java
pom.xml
retrievaltool/src/main/java/org/duracloud/retrieval/mgmt/RetrievalWorker.java
retrievaltool/src/test/java/org/duracloud/retrieval/source/DuraStoreRetrievalSourceTest.java
s3storageprovider/src/main/java/org/duracloud/s3storage/S3ProviderUtil.java
stitch/src/main/java/org/duracloud/stitch/FileStitcherDriver.java
stitch/src/test/java/org/duracloud/stitch/impl/FileStitcherImplTest.java
stitch/src/test/java/org/duracloud/stitch/stream/MultiContentInputStreamTest.java
synctool/src/main/java/org/duracloud/sync/config/SyncToolConfigParser.java
synctool/src/main/java/org/duracloud/sync/endpoint/FileSystemSyncEndpoint.java

**JIRA Ticket**: https://duracloud.atlassian.net/browse/DURACLOUD-1292
Updates dependencies used by DuraCloud as well as the Management Console, Mill, and Snapshot projects.
There should be no functional changes. If the applications build, deploy, pass tests, and work as normal, then these changes were successful.
A change to the default stream copy buffer in commons-io caused the chunking process to fail. To resolve this I set the buffer explicitly to the old value (4096) in the IOUtil utility class and updated code that had been using the commons-io class directly to use IOUtil instead.

DURACLOUD-1292: Updates dependency versions

---

common-changenotifier/src/main/java/org/duracloud/common/changenotifier/SnsSubscriptionManager.java

**JIRA Ticket**: https://duracloud.atlassian.net/browse/DURACLOUD-1319
Extends the retry timeline for creating the notification queue to accommodate the AWS requirement that queues of the same name that are deleted and recreated must have a 60 second window between these actions.
Have the DuraCloud apps running locally. Run a build and allow them to be redeployed. Verify that the apps launch properly after the rebuild (without needing a container restart).

DURACLOUD-1319: Resolves app launch failure due to notification queue recreation

---

snapshotdata/src/main/java/org/duracloud/snapshot/dto/bridge/GetSnapshotCountBridgeResult.java
snapshotdata/src/main/java/org/duracloud/snapshot/dto/bridge/GetSnapshotTotalCountBridgeResult.java
snapshotdata/src/main/java/org/duracloud/snapshot/dto/bridge/GetSnapshotTotalFilesBridgeResult.java
snapshotdata/src/main/java/org/duracloud/snapshot/dto/bridge/GetSnapshotTotalSizeBridgeResult.java
snapshotdata/src/main/java/org/duracloud/snapshot/dto/bridge/GetSnapshotTotalsBridgeResult.java

**This PR works in tandem with the snapshot repository PR for new endpoints – https://github.com/duracloud/snapshot/pull/30. It adds three Bridge result classes for the new REST API endpoints that provide total snapshot count, snapshot size and snapshot files.**
* * *
**JIRA Ticket**: https://duracloud.atlassian.net/browse/DURACLOUD-1150
* Build and install (push to local maven repository) this PR
* Build and deploy the Bridge from https://github.com/duracloud/snapshot/pull/30

DURACLOUD-1150: Add REST API endpoints for total size and files in snapshots

---

retrievaltool/pom.xml
retrievaltool/src/main/java/org/duracloud/retrieval/source/DuraStoreRetrievalSource.java
retrievaltool/src/main/java/org/duracloud/retrieval/source/DuraStoreSpecifiedRetrievalSource.java
retrievaltool/src/test/java/org/duracloud/retrieval/source/DuraStoreSpecifiedRetrievalSourceTest.java

**This PR changes the DuraStoreSpecifiedRetrievalSource class so that when a list-file is specified it creates a full list of contentIds to be retrieved, including any chunked content of files in the list-file.**
* * *
**JIRA Ticket**: https://duracloud.atlassian.net/browse/DURACLOUD-1268
This PR changes the class used by the RetrievalTool when a list-file is specified to work more like the default behavior when retrieving a space. As as result of this change, the two classes can now retrieve content with the same function. This PR resolves the case where the RetrievalTool with a list-file specified fails to transfer when restarting from partially chunked files.
* Create a space in DuraCloud and use the SyncTool to add one or more large files that will be chunked
* Use the version 7.0 of …

DURACLOUD-1268: refactor the RetrievalTool to create full list of contentIds, including chunked content, when a list-file is used

---

pom.xml
synctoolui/src/main/java/org/duracloud/syncui/service/RuntimeStateMemento.java
synctoolui/src/main/java/org/duracloud/syncui/service/SyncToolConfigSerializer.java

**JIRA Ticket**: https://duracloud.atlassian.net/browse/DURACLOUD-1317
Updates the xstream dependency to version 1.4.18 due to a security notice in 1.4.17.
There are no functional changes. So long as the application continues to work, we're good.

DURACLOUD-1317: Updates xstream dependency

---

.github/workflows/ci-build.yml
pom.xml

**JIRA Ticket**: https://duracloud.atlassian.net/browse/DURACLOUD-1278
Adds a build of the DuraCloud application executed by Github Actions. On failure a notice is set to Slack. On success or failure an email notification is sent. When the build is run on the develop or main branch the result is pushed to Sonatype.
A build should be run and available to view in Github for each commit in this PR. When the PR is merged, it should run a build on develop.
This PR leaves the Travis CI configuration in place to serve as reference when adding a Github Action to capture release artifacts.

DURACLOUD-1278: Adds Github Actions build to replace Travis CI

---

duradmin/src/main/java/org/duracloud/duradmin/spaces/controller/SnapshotController.java
duradmin/src/main/webapp/jquery/dc/api/durastore-api.js
duradmin/src/main/webapp/js/spaces-manager.js
snapshotdata/src/main/java/org/duracloud/snapshot/SnapshotConstants.java
snapshotdata/src/main/java/org/duracloud/snapshot/dto/task/GetSnapshotsTotalsTaskParameters.java
snapshotdata/src/main/java/org/duracloud/snapshot/dto/task/GetSnapshotsTotalsTaskResult.java
snapshotstorageprovider/src/main/java/org/duracloud/snapshottask/SnapshotTaskProvider.java
snapshotstorageprovider/src/main/java/org/duracloud/snapshottask/snapshot/GetSnapshotsTotalsTaskRunner.java
snapshotstorageprovider/src/test/java/org/duracloud/snapshottask/snapshot/GetSnapshotsTotalsTaskRunnerTest.java
storeclient/src/main/java/org/duracloud/client/task/SnapshotTaskClient.java
storeclient/src/main/java/org/duracloud/client/task/SnapshotTaskClientImpl.java
storeclient/src/test/java/org/duracloud/client/task/SnapshotTaskClientImplTest.java

**This PR builds on the work of [DURACLOUD-1150](https://github.com/duracloud/duracloud/pull/148) to present information about snapshots (total count, size and files) in the UI.**
* * *
**JIRA Ticket**: https://duracloud.atlassian.net/browse/DURACLOUD-1279
* https://duracloud.atlassian.net/browse/DURACLOUD-1150
* https://github.com/duracloud/snapshot/pull/30
This PR adds a snapshot totals pane to the GUI for snapshot storage providers when no spaces are selected. It uses the API calls added in DURACLOUD-1150 to get the statistics. 
* Deploy DuraCloud and select a storage provider such as Chronopolis to see the stats
* Compare the values with what's in your Bridge's database, substituting your host for $HOST:
* `SELECT COUNT(id) FROM snapshot WHERE host = '$HOST' AND status = …

DURACLOUD-1279: Adds snapshot totals information to the UI, companion PR to DURACLOUD-1150

---

pom.xml
storeclient/src/main/java/org/duracloud/client/ContentIterator.java
synctool/src/main/java/org/duracloud/sync/endpoint/DuraStoreSyncEndpoint.java
synctool/src/test/java/org/duracloud/sync/endpoint/DuraStoreChunkSyncEndpointTest.java
synctool/src/test/java/org/duracloud/sync/endpoint/DuraStoreSyncEndpointTest.java
synctoolui/src/test/java/org/duracloud/syncui/service/SyncProcessManagerImplTest.java

**Fixes [DURACLOUD-1313](https://duracloud.atlassian.net/browse/DURACLOUD-1313)**
* * *
Also includes additional commit that bumps hibernate version to resolve [this issue](https://github.com/spring-projects/spring-boot/issues/11225).

DURACLOUD-1313: Stops synctool retrying hundreds of times

---

durastore/src/main/java/org/duracloud/durastore/rest/StorageStatsResource.java

**Addresses incompatibilities with mysql 8.x**
* * *
**JIRA Ticket**:https://duracloud.atlassian.net/browse/DURACLOUD-1298
Makes the storage report API compatible with mysql 8.  This change should be backwards compatible.
Deploy against mysql 8.x
Navigate to a space in duradmin.
Verify that the storage reports are visible and no errors are displayed.
To reproduce the error, run without this change against mysql 8 - the duradmin UI will report a failure to display the time series.

Addresses incompatibilities with mysql 8.x

---

resources/beanstalk/.platform/httpd/conf.d/elasticbeanstalk.conf

Sample Elastic Beanstalk config – https://github.com/awsdocs/elastic-beanstalk-samples/blob/main/configuration-files/aws-provided/security-configuration/https-redirect/java-tomcat/https-redirect-java-tomcat-apache-2.4/httpd/conf.d/elasticbeanstalk.conf

Fixes issue with EB health checker falsely reporting severe status

---

duradmin/src/main/webapp/WEB-INF/config/security-config.xml
durastore/src/main/webapp/WEB-INF/config/security-config.xml

The update to Spring Security 4.2 introduced the default usage of StrictHttpFirewall. This PR adjusts those default settings to allow percent and semicolon characters to be included in valid calls to the DuraCloud UI and REST API.
Add content to DuraCloud that includes percent and semicolon symbols in the content ID. Ensure that the content can be retrieved and used without error.

Tells spring security to allow URLs with percent and semicolon characters

---

duradmin/src/main/resources/messages_en.properties
duradmin/src/main/webapp/jquery/dc/ext/jquery.dc.common.js

After https://github.com/duracloud/duracloud/pull/157 they're no longer needed.

Removes two references to IRODS storage provider

---

swiftstorageprovider/src/main/java/org/duracloud/swiftstorage/SwiftStorageProvider.java

Omitting this header was causing integration tests to fail, so Adding it
as an allowed header for the SwiftS3 storage provider.
* Run integration tests against a build before this change. Observe that the integration tests fail.
* Build with this change and run integration tests again. Observe that the integration tests succeed.
* Observe that the metadata list in the UI is unaffected.

Add CONTENT_RANGE as a permissible Swift header

---

pom.xml

The default is 5 minutes.   I noticed that this timeout was being exceeded on occasion during the release process so I bumped it up to 10 minutes.

Increases sonatype upload timeout.

---

common/src/main/java/org/duracloud/common/web/RestHttpHelper.java

**This PR changes the cookie specification in the HTTP Client from DEFAULT to STANDARD in order to prevent warnings about the format of the date in cookies sent from the AWS Application Load Balancer.**
* * *
**JIRA Ticket**: https://duracloud.atlassian.net/browse/DURACLOUD-1333
* Reproduce the problem you are fixing (if applicable)
* Test that the Pull Request does what is intended.
* Please be as detailed as possible.
* Good testing instructions help get your PR completed faster. …

DURACLOUD-1333: Change cookie specification to STANDARD to accommodate more date formats

---

resources/beanstalk/.ebextensions/sumo_logic.config

This update ensures the sumo sources json is being placed in the /opt/dir directory by the beanstalk configuration.

Put sumo_sources.json in the /opt/ dir

---

retrievaltool/src/main/java/org/duracloud/retrieval/mgmt/RetrievalManager.java

**JIRA Ticket**: https://duracloud.atlassian.net/browse/DURACLOUD-1069
This updates the shutdown logic of the RetrievalManager to use a phaser to track work completion instead of using awaitTermination.
* Rebuild the retrieval tool
* Run the tool on a large-ish space
* When the final status message is printed there should no longer be any retrievals in progress
I was considering using `submit` to return a future and do a get on each to emulate joining the threads, but wasn't sure what the typical space would look like and didn't want a growing list of futures. Not a big deal just an alternate solution which might be a _little_ bit simpler. 

Retrieval Tool: Indicates "complete" before all transfers finish

---

.github/workflows/ci-build.yml

This is a follow to the recent java 17 updates (missed a couple of java 11 references).

Update the sonatype publish and signing routines to use java 17

---

duradmin/src/main/webapp/WEB-INF/web.xml

**JIRA Ticket**: n/a
* Increase the default session timeout for duradmin webappp
n/a
The session timeout for the duradmin project was updated in our deployment to better support some user workflows; this aligns the setting here so we don't need to update it during each release. 
@dbernstein

Increase default session timeout

---

.github/workflows/ci-build.yml
durastore/src/main/java/org/duracloud/durastore/rest/StorageStatsResource.java
durastore/src/test/java/org/duracloud/durastore/rest/StorageStatsResourceTest.java

**JIRA Ticket**: https://duracloud.atlassian.net/browse/DURACLOUD-1355
* Sort timeseries data returned by StorageStatsResource
* Run the test in StorageStatsResourceTest.java to verify stats are sorted when returned from the endpoint
* Bonus: Remove the sort and verify the tests fail
I had trouble actually getting the stats to be unordered in order to test this properly. I initially wanted to make this change in the `duracloud-db` project and use an order by clause when fetching from the database, but even after inserting out of order, my queries were returning in order.
I also opted to do this in the `StorageStatsResource` as opposed the `StorageStatsController` because the controller is really just deserializing/serializing the data that comes from the api updated here. The lists …

DC-1355: Sort timerseries data
