duracloud/duracloud

- duradmin/src/main/webapp/js/spaces-manager.js
Fixes snapshot-detection bug in JS that may have been introduced in 3.3.0.
> Fixed bug in spaces-manager.js that was introduced with 3.3.0

- retrievaltool/src/main/java/org/duracloud/retrieval/config/RetrievalConfig.java
There we go. An errant merge somewhere must have gotten me ahead of the remote branch.
> fixed misspelled work folder

- duradmin/src/main/webapp/WEB-INF/jsp/spaces/spaces-manager.jsp
- duradmin/src/main/webapp/jquery/dc/widget/ui.uploader.js
- duradmin/src/main/webapp/style/main.css
Resolves https://jira.duraspace.org/browse/DURACLOUD-1110
> Prevent user from uploading files larger than 2GB.

- pom.xml
- s3storageprovider/src/main/java/org/duracloud/s3task/streaming/GetSignedUrlTaskRunner.java
- s3storageprovider/src/test/java/org/duracloud/s3task/streaming/DeleteStreamingTaskRunnerTest.java
Resolves: https://jira.duraspace.org/browse/DURACLOUD-1117
> Updates the AWS SDK version

- s3storageprovider/src/main/java/org/duracloud/s3storage/S3StorageProvider.java
- s3storageprovider/src/test/java/org/duracloud/s3storage/S3StorageProviderTest.java
are properly encoded.
Resolves: https://jira.duraspace.org/browse/DURACLOUD-1130
> Ensures that http header values sent to s3 via the aws sdk

- synctool/src/main/java/org/duracloud/sync/SyncTool.java
- synctool/src/main/java/org/duracloud/sync/walker/DirWalker.java
- synctool/src/main/java/org/duracloud/sync/walker/RestartDirWalker.java
- synctool/src/test/java/org/duracloud/sync/SyncTestBase.java
- synctool/src/test/java/org/duracloud/sync/walker/DirWalkerTest.java
- synctool/src/test/java/org/duracloud/sync/walker/RestartDirWalkerTest.java
- synctoolui/src/main/java/org/duracloud/syncui/service/SyncProcessManagerImpl.java
exclusion checks in the DirWalker in addition to existing checks in the ChangedList.
Resolves: https://jira.duraspace.org/browse/DURACLOUD-1133
> Ensures efficiency of directory and file exclusion by reintroducing

- .travis.yml
- storeclient/src/main/java/org/duracloud/client/ContentStoreImpl.java
Resolves https://jira.duraspace.org/browse/DURACLOUD-1137
> Ensures bit integrity reports can be downloaded from duradmin.

- common/src/main/java/org/duracloud/common/util/ChecksumUtil.java
- common/src/test/java/org/duracloud/common/util/ChecksumUtilTest.java
Resovles: https://jira.duraspace.org/browse/DURACLOUD-1151
> ChecksumUtil produces correct checksum after IO failure.

- retrievaltool/files.txt
- retrievaltool/src/main/java/org/duracloud/retrieval/mgmt/RetrievalManager.java
- retrievaltool/src/main/java/org/duracloud/retrieval/mgmt/RetrievalWorker.java
- retrievaltool/src/main/java/org/duracloud/retrieval/source/DuraStoreRetrievalSource.java
- retrievaltool/src/main/java/org/duracloud/retrieval/source/DuraStoreStitchingRetrievalSource.java
- retrievaltool/src/main/resources/logback.xml
- retrievaltool/src/test/java/org/duracloud/retrieval/source/DuraStoreRetrievalSourceTest.java
Resolves https://jira.duraspace.org/browse/DURACLOUD-1152
> Duracloud 1152

- retrievaltool/src/main/resources/logback.xml
Resolves: https://jira.duraspace.org/browse/DURACLOUD-1171
> Reorganizes RetrievalTool logback file to resolve error

- resources/travis/before-install.sh
- resources/travis/mvndeploy-settings.xml
Also changes download path to pull from DuraCloud (dcprod) so as to ensure that a consistent version is retrieved
> Updates InstallBuilder version to 17.12.0

- duradmin/src/main/java/org/duracloud/duradmin/spaces/controller/SnapshotController.java
- duradmin/src/main/webapp/jquery/dc/widget/ui.snapshot.js
- durastore/src/main/java/org/duracloud/durastore/rest/TaskRest.java
- snapshotstorageprovider/src/main/java/org/duracloud/snapshottask/snapshot/AbstractSnapshotTaskRunner.java
- snapshotstorageprovider/src/main/java/org/duracloud/snapshottask/snapshot/CreateSnapshotTaskRunner.java
- snapshotstorageprovider/src/test/java/org/duracloud/snapshottask/snapshot/CreateSnapshotTaskRunnerTest.java
- storageprovider/src/main/java/org/duracloud/storage/error/ServerConflictException.java
- storeclient/src/main/java/org/duracloud/client/ContentStoreImpl.java
Resovled:  https://jira.duraspace.org/browse/DURACHRON-169
You can observe the new behavior on danny.duracloud.org.
> Ensures that snapshot errors display descriptive messages.

- README.md
Two changes to the Why DuraCloud section and one change to the Overview section. Let me know what you think! ~ Erin
> three small text edits to README

- snapshotdata/src/main/java/org/duracloud/snapshot/dto/task/CreateSnapshotTaskParameters.java
- snapshotdata/src/test/java/org/duracloud/snapshot/dto/bridge/CreateSnapshotBridgeParametersTest.java
Resolves: https://jira.duraspace.org/browse/DURACLOUD-1080
> Snapshot no longer fails when triggered from UI without description.

- duradmin/src/main/java/org/duracloud/duradmin/domain/Space.java
- duradmin/src/main/java/org/duracloud/duradmin/domain/SpaceProperties.java
- duradmin/src/main/java/org/duracloud/duradmin/spaces/controller/ContentItemController.java
- duradmin/src/main/java/org/duracloud/duradmin/spaces/controller/MediaStreamingTaskController.java
- duradmin/src/main/java/org/duracloud/duradmin/util/SpaceUtil.java
- duradmin/src/main/webapp/WEB-INF/jsp/spaces/spaces-manager.jsp
- duradmin/src/main/webapp/jquery/dc/api/durastore-api.js
- duradmin/src/main/webapp/jquery/dc/widget/ui.streaming.js
- duradmin/src/main/webapp/js/spaces-manager.js
- duradmin/src/main/webapp/style/base.css
- duradmin/src/test/java/org/duracloud/duradmin/spaces/controller/MediaStreamingServiceControllerTest.java
- storeclient/src/main/java/org/duracloud/client/ContentStore.java
- storeclient/src/main/java/org/duracloud/client/task/S3TaskClient.java
- storeclient/src/main/java/org/duracloud/client/task/S3TaskClientImpl.java
- storeclient/src/test/java/org/duracloud/client/task/S3TaskClientImplTest.java
partial resolution of https://jira.duraspace.org/browse/DURACLOUD-1188
> Adds duradmin and storeclient support for hls streaming in

- duradmin/src/main/webapp/jquery/dc/widget/ui.streaming.js
- duradmin/src/main/webapp/js/spaces-manager.js
- duradmin/src/main/webapp/style/base.css
ensures that the panel is automatically refreshed when the streaming
is switched on or off.
> Moves the streaming properties to the Streaming control panel and

- durastore/src/main/java/org/duracloud/durastore/rest/AuxRest.java
- durastore/src/main/webapp/WEB-INF/config/restapi-config.xml
- durastore/src/test/java/org/duracloud/durastore/rest/AuxRestTest.java
- s3storageprovider/src/main/java/org/duracloud/s3storage/S3StorageProvider.java
- s3storageprovider/src/main/java/org/duracloud/s3storage/StringDataStoreFactory.java
- s3storageprovider/src/test/java/org/duracloud/s3storage/S3StorageProviderTest.java
- s3storageprovider/src/test/java/org/duracloud/s3storage/StringDataStoreTest.java
> Adds unit tests for AuxRest, new S3StorageProvider methods,

- durastore/src/main/java/org/duracloud/durastore/util/ACLStorageProvider.java
This is just a small update to improve logging when the cacheloader fails.
> Adds logging to indicate when the CacheLoader has failed to complete.

- duradmin/src/main/webapp/jquery/dc/ext/jquery.fn.ext.js
- duradmin/src/main/webapp/jquery/dc/widget/ui.tagsviewer.js
- pom.xml
**Adding and displaying tags in the UI works again.**
* * *
**JIRA Ticket**: https://jira.duraspace.org/browse/DURACLOUD-1212
@bbranan , @duracloud/committers
> Duracloud 1212

- common/pom.xml
- pom.xml
- synctoolui/pom.xml
**JIRA Ticket**: https://jira.duraspace.org/browse/DURACLOUD-1217
Updates the dependency version used for Jetty for tests in the common package to be consistent with the Jetty version used in the SyncTool.
There are no functional changes to this code. If the Travis tests pass, then it's good to go.
Example:
Tag (@ mention) …
> DURACLOUD-1217: Updates Jetty test dependency version in common

- pom.xml
**JIRA Ticket**: https://jira.duraspace.org/browse/DURACLOUD-1218
Updates the version of the commons-fileupload dependency.
Verify that file uploads still function properly
* Could this change impact execution of existing code? Yes
@dbernstein
> DURACLOUD-1218: Updates commons-fileupload dependency version

- pom.xml
- s3storageprovider/src/main/java/org/duracloud/s3storage/S3StorageProvider.java
- storeclient/src/main/java/org/duracloud/client/task/S3TaskClient.java
and anchors duraspace checkstyle to tagged version.
> Updates com.puppycrawl.tools.checkstyle dependency

- duradmin/src/main/webapp/js/spaces-manager.js
**Remove all event listeners on delete space button to ensure there aren't multiple multi-space delete listeners.**
* * *
**JIRA Ticket**: https://jira.duraspace.org/browse/DURACLOUD-1192
* Reproduce the problem you are fixing (if applicable)
* Test that the Pull Request does what is intended.
* Please be as detailed as possible.
* Good testing instructions help get your PR completed faster.
Example:
* Does this change add any …
> Duracloud 1192b: fixes bug introduced by PR to change space deletion process

- irodsstorageprovider/pom.xml
**The title of this pull-request should be a brief description of what the pull-request fixes/improves/changes. Ideally 50 characters or less.**
* * *
**JIRA Ticket**: https://jira.lyrasis.org/browse/DURACLOUD-1249
Replaces the UMIACS maven repo with the UCSD maven repo
Verify that the build passes.
@dbernstein
> DURACLOUD-1249: Updates maven repo for IRODS dependency

- pom.xml
Also updates organization from DuraSpace to LYRASIS and reference urls to https
**The title of this pull-request should be a brief description of what the pull-request fixes/improves/changes. Ideally 50 characters or less.**
* * *
**JIRA Ticket**: None
https://blog.sonatype.com/central-repository-moving-to-https
Updates the Maven central repository URL to use HTTPS rather than HTTP. Also updates a few reference URLs to use HTTPS as well. Changes the organization name from DuraSpace to LYRASIS.
If the build passes, then we're in good shape.
> Updates URL for Maven central to use https

- duradmin/src/main/java/org/duracloud/duradmin/util/SpaceUtil.java
- durastore/src/test/java/org/duracloud/durastore/rest/StorageStatsResourceTest.java
- pom.xml
- synctool/src/main/java/org/duracloud/sync/endpoint/DuraStoreChunkSyncEndpoint.java
Updates a few lines to conform to line length limits enforce in codestyle 1.0.1
No functional changes
> Updates codestyle to version 1.0.1

- common/src/main/java/org/duracloud/common/util/DuracloudConfig.java
- common/src/main/java/org/duracloud/common/util/DuracloudConfigBean.java
- duradmin/src/main/java/org/duracloud/duradmin/control/LoginController.java
- durastore/src/main/java/org/duracloud/durastore/rest/AuxRest.java
- durastore/src/test/java/org/duracloud/durastore/rest/AuxRestTest.java
- notification-smtp/src/main/java/org/duracloud/notification/SMTPEmailer.java
- notification-smtp/src/main/java/org/duracloud/notification/SMTPNotificationFactory.java
- pom.xml
- swiftstorageprovider/src/test/java/org/duracloud/swiftstorage/SwiftStorageProviderTest.java
Minor formatting updates, no functional changes beyond the use of the new codestyle version.
> DURACLOUD-1259: Updates codestyle to v1.1.0

- .travis.yml
- auditor/src/test/java/org/duracloud/audit/provider/AuditStorageProviderTest.java
- auditor/src/test/java/org/duracloud/audit/reader/impl/AuditLogReaderImplTest.java
- chunk/pom.xml
- common-json/pom.xml
- common-xml/pom.xml
- durastore/src/test/java/org/duracloud/durastore/rest/ContentResourceImplTest.java
- durastore/src/test/java/org/duracloud/durastore/util/ACLStorageProviderTest.java
- glacierstorageprovider/src/test/java/org/duracloud/glacierstorage/GlacierStorageProviderTest.java
- notification-amazon/src/test/java/org/duracloud/notification/AmazonEmailerTest.java
- pom.xml
- reportdata/pom.xml
- s3storageprovider/src/test/java/org/duracloud/s3storage/S3StorageProviderTest.java
- s3storageprovider/src/test/java/org/duracloud/s3task/streaming/EnableStreamingTaskRunnerTest.java
- s3storageprovider/src/test/java/org/duracloud/s3task/streaming/StreamingTaskRunnerTestBase.java
- security/pom.xml
- snapshotstorageprovider/src/test/java/org/duracloud/snapshottask/snapshot/CleanupSnapshotTaskRunnerTest.java
- snapshotstorageprovider/src/test/java/org/duracloud/snapshottask/snapshot/CompleteCancelSnapshotTaskRunnerTest.java
- snapshotstorageprovider/src/test/java/org/duracloud/snapshottask/snapshot/CompleteRestoreTaskRunnerTest.java
- snapshotstorageprovider/src/test/java/org/duracloud/snapshottask/snapshot/CreateSnapshotTaskRunnerTest.java
- snapshotstorageprovider/src/test/java/org/duracloud/snapshottask/snapshot/RestoreSnapshotTaskRunnerTest.java
- storageprovider/src/test/java/org/duracloud/storage/provider/StorageProviderBaseTest.java
- storeclient/src/test/java/org/duracloud/client/ContentStoreImplTest.java
- swiftstorageprovider/src/test/java/org/duracloud/swiftstorage/SwiftStorageProviderTest.java
- syncoptimize/src/test/java/org/duracloud/syncoptimize/test/SyncTesterTest.java
- synctool/src/test/java/org/duracloud/sync/endpoint/DuraStoreChunkSyncEndpointTest.java
- synctool/src/test/java/org/duracloud/sync/endpoint/DuraStoreSyncEndpointTest.java
**JIRA Ticket**: https://jira.lyrasis.org/browse/DURACLOUD-1242
Updates DuraCloud to build and run with Java 11
There should be no functional changes. Testing should include building with Java 11 and running in a Tomcat that is also using Java 11. The more testing to verify that everything is working properly, the better.
@dbernstein 
@nwoodward
> Updates DuraCloud to build and run with Java 11

- synctoolui/src/main/webapp/WEB-INF/jsp/configuration.jsp
- synctoolui/src/main/webapp/WEB-INF/jsp/template/app-base.jsp
- synctoolui/src/main/webapp/WEB-INF/jsp/template/page-base.jsp
- synctoolui/src/main/webapp/static/css/global.css
- synctoolui/src/main/webapp/static/js/configuration.js
**JIRA Ticket**: https://jira.lyrasis.org/browse/DURACLOUD-1265
Changes to HTML and CSS of SyncTool UI to improve accessibility as measured by the WAVE Accessibility Evaluation Tool.
Build DuraCloud and run the SyncTool UI. Compare the results between the 'develop' branch and this PR using the WAVE extension for your browser. 
> Duracloud-1265: Improve accessibility of SyncTool UI

- duradmin/src/main/webapp/WEB-INF/jsp/include/footer.jsp
- duradmin/src/main/webapp/WEB-INF/jsp/layout/v2/base-layout.jsp
- duradmin/src/main/webapp/WEB-INF/jsp/layout/v2/base.jsp
- duradmin/src/main/webapp/WEB-INF/jsp/login-v2.jsp
- duradmin/src/main/webapp/WEB-INF/jsp/spaces/spaces-manager.jsp
- duradmin/src/main/webapp/jquery/dc/widget/ui.expandopanel.js
- duradmin/src/main/webapp/jquery/dc/widget/ui.historypanel.js
- duradmin/src/main/webapp/jquery/dc/widget/ui.propertiesviewer.js
- duradmin/src/main/webapp/jquery/dc/widget/ui.selectablelist.js
- duradmin/src/main/webapp/jquery/dc/widget/ui.tagsviewer.js
- duradmin/src/main/webapp/js/spaces-manager.js
- duradmin/src/main/webapp/style/base.css
- duradmin/src/main/webapp/style/buttons.css
- duradmin/src/main/webapp/style/login.css
**Improves accessiibility of DuraCloud**
* * *
**JIRA Ticket**: https://jira.lyrasis.org/browse/DURACLOUD-1264
Tweaks the UI to reduce accessibility related deficiencies including contrast errors, unlabelled form elements and other similar issues that reduce the accessibility of the page.
Run duradmin with the WAVE tool.  See all the errors that were fixed.
> Improve DuraCloud Accessibility

- duradmin/src/main/webapp/WEB-INF/jsp/spaces/spaces-manager.jsp
** Fixes broken add space and copy content item functionality.  **
* * *
**JIRA Ticket**: https://jira.lyrasis.org/browse/DURACLOUD-1282
Fixes the problems Nick discovered that were caused by the accessibility updates.
1. Try to create a space via duradmin.  Validate that you can. 
2. Try to copy a content item.  Verify that the spaces drop down gets populated  that you can successfully perform a copy operation.
> Fixes broken add space and copy content item functionality.

- synctoolui/README
**JIRA Ticket**: https://jira.lyrasis.org/browse/DURACLOUD-1283
> Updates synctoolui readme to indicated java 11 requirement.

- common/src/main/java/org/duracloud/common/util/DateUtil.java
- pom.xml
Resolves: https://jira.lyrasis.org/browse/DURACLOUD-1287
> Set locale in main pom.xml

- pom.xml
> Update DuraCloud db dependency to 6.3.0-SNAPSHOT.

- common-changenotifier/src/main/java/org/duracloud/common/changenotifier/SnsSubscriptionManager.java
**Check for existence of queues before attempting to create them.**
* * *
**JIRA Ticket**: https://jira.lyrasis.org/browse/DURACLOUD-1299
Simply checks for the existence of a change notification queue before trying to create it.  
Build and redeploy on aws:  verify that the application comes up without having to terminate the existing instances.
Example:
* Does this change add any new dependencies? 
* Does this change require any other modifications to be made to the repository (ie. Regeneration activity, etc.)? 
* Could this change impact execution of existing code?
Tag (@ …
> Check for existence of queues before attempting to create them.

- duradmin/src/main/webapp/WEB-INF/jsp/login-v2.jsp
**Fixes broken link on login page.**
* * *
**JIRA Ticket**: https://duracloud.atlassian.net/browse/DURACLOUD-1297
Deployed on dev: https://danny.duracloud.org/duradmin/spaces/sm/52/blah-blah 
Verify the duracloud image link is not broken.
Example:
* Does this change add any new dependencies? 
* Does this change require any other modifications to be made to the repository (ie. Regeneration activity, etc.)? 
* Could this change impact execution of existing code?
Tag (@ mention) …
> Remove broken image on login screen

- snapshotstorageprovider/src/main/java/org/duracloud/snapshottask/snapshot/AbstractSnapshotTaskRunner.java
- snapshotstorageprovider/src/main/java/org/duracloud/snapshottask/snapshot/CreateSnapshotTaskRunner.java
See: https://duracloud.atlassian.net/browse/DURACLOUD-1308
Also adds additional logging, to better understand why snapshot creation failures occur.
> DURACLOUD-1308: Adds check for valid snapshot after a snapshot create failure

- duradmin/src/main/webapp/WEB-INF/config/security-config.xml
- durastore/src/main/webapp/WEB-INF/config/security-config.xml
- pom.xml
This update is dependent on this PR: https://github.com/duracloud/duracloud-db/pull/30
> Fix dependency and build issues

- duradmin/src/main/webapp/WEB-INF/jsp/layout/v2/base-layout.jsp
- duradmin/src/main/webapp/WEB-INF/jsp/spaces/upload-tool.jsp
- synctoolui/src/main/webapp/WEB-INF/jsp/template/app-base.jsp
Minimal cosmetic change:  updates synctool and duradmin to reference lyrasis rather than duraspace.
> Replaces user visible duraspace references with lyrasis.

- pom.xml
> Upgrade to Sonatype's new build infrastructure.

- duradmin/src/main/java/org/duracloud/duradmin/security/BinderControllerAdvice.java
**The title of this pull-request should be a brief description of what the pull-request fixes/improves/changes. Ideally 50 characters or less.**
* * *
**JIRA Ticket**: (link)
* Reproduce the problem you are fixing (if applicable)
* Test that the Pull Request does what is intended.
* Please be as detailed as possible.
* Good testing instructions help get your PR completed faster.
Example:
* Does this change add any new …
> Addresses spring issue.

- synctoolui/src/main/webapp/static/js/jqueryFileTree.js
**The title of this pull-request should be a brief description of what the pull-request fixes/improves/changes. Ideally 50 characters or less.**
* * *
**JIRA Ticket**: (link)
* Reproduce the problem you are fixing (if applicable)
* Test that the Pull Request does what is intended.
* Please be as detailed as possible.
* Good testing instructions help get your PR completed faster.
Example:
* Does this change add any new …
> Modifies JS library to facilitate selecting directories as well as files

- durastore/src/test/java/org/duracloud/durastore/util/ACLStorageProviderTest.java
- pom.xml
Testing for error in `ACLStorageProviderTest` during CI
* Check that CI is passing
* Make sure all tests still pass locally: `mvn clean install -DskipIntTests -DskipDeploy`
Currently just using this PR to test the CI env for this repo. If everything is passing I need to go through and clean up the commits
> CI Build Failure

- .github/workflows/ci-build.yml
- pom.xml
- synctool/pom.xml
- synctoolui/pom.xml
**JIRA Ticket**: https://duracloud.atlassian.net/browse/DURACLOUD-1340
Updates the build to use java 17
tbd
Tag (@ mention) interested parties or, if unsure, @duracloud/committers, @nwoodward
> Compile to Java 17

- pom.xml
Part of the dependency update.
> Upgrade logging.

- pom.xml
**This PR updates the embedded Jetty server in the Sync Tool UI to the most recent 9.4.x release of Jetty. No code changes are required.**
* * *
**JIRA Ticket**: N/A
Build the Sync Tool UI and run a few test sync jobs.
> Update embedded Jetty server in the Sync Tool UI to latest 9.4 release

- common-changenotifier/pom.xml
- common-queue/pom.xml
> Remove unnecessary rabbit dependency version references.

- pom.xml
This update fixes a problem with deploying releases.
> Update nexus staging plugin

- duradmin/src/main/webapp/jquery/dc/api/durastore-api.js
- duradmin/src/main/webapp/js/spaces-manager.js
**JIRA Ticket**: https://duracloud.atlassian.net/browse/DURACLOUD-1305
Deploy this PR and observe that the odd behavior described in the Jira issue no longer occurs. 
> DURACLOUD-1305: adds check to make sure the space to be added does not already exist
